### ISSUE TITLE
breaks calculated values

### ISSUE THREAD

**Issue by garretwilson** [samaxes/minify-maven-plugin#161]
My source file has this:

```css
.foo {
  font-size: calc(0.5em + 1vw);
}
```

The plugin changes this to:

```css
.foo{font-size:calc(0.5em+1vw)}
```

This is invalid and breaks the value.

This is is a blocker issue. The plugin is broken; I cannot use it.
